In [ ]:
# Bioactivity data for target CHEMBL4333 (Sphingosine 1-phosphate receptor 1)
# https://www.ebi.ac.uk/chembl/explore/activities/STATE_ID:SGbYPQS862ex-pt4OGGNjQ%3D%3D
# Raw data obtained from chembl manually

In [224]:
!pip install rdkit

Requirement already satisfied: rdkit in /usr/local/lib/python3.12/dist-packages (2025.3.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)

In [225]:
import pandas as pd
data = pd.read_csv('/content/DOWNLOAD-bMvTskxhFg6a9hkRROdQerj2G5k0QhOkPXtZhAszrPs_eq_.csv', delimiter=';')
data.head()

,Molecule ChEMBL ID,Molecule Name,Molecule Max Phase,Molecular Weight,#RO5 Violations,AlogP,Compound Key,Smiles,Standard Type,Standard Relation,...,Document ChEMBL ID,Source ID,Source Description,Document Journal,Document Year,Cell ChEMBL ID,Properties,Action Type,Standard Text Value,Value
0,CHEMBL4092538,NaN,NaN,421.54,0.0,4.57,13m,CCc1ccc(COc2ccc3c(c2)CCC(CN2CC(C(=O)O)C2)=C3C)...,EC50,'=',...,CHEMBL4028892,1,Scientific Literature,J Med Chem,2017.0,NaN,NaN,NaN,NaN,0.58
1,CHEMBL389033,NaN,NaN,370.43,0.0,3.42,"12d, VPC44116",CCCCCCCCc1cccc(NC(=O)[C@H](N)CCP(=O)(O)O)c1,Ki,'=',...,CHEMBL1144572,1,Scientific Literature,Bioorg Med Chem,2007.0,CHEMBL3706569,NaN,NaN,NaN,30.00
2,CHEMBL228137,NaN,NaN,358.42,0.0,3.90,19,CCCCCCCCc1ccc(OC[C@@H](O)CCP(=O)(O)O)cc1,Emax,'=',...,CHEMBL1144572,1,Scientific Literature,Bioorg Med Chem,2007.0,CHEMBL3706569,NaN,NaN,NaN,0.43
3,CHEMBL228049,NaN,NaN,329.38,0.0,3.08,18b,CCCCCCc1ccc(OC[C@H](N)CCP(=O)(O)O)cc1,Emax,'=',...,CHEMBL1144572,1,Scientific Literature,Bioorg Med Chem,2007.0,CHEMBL3706569,NaN,NaN,NaN,0.64
4,CHEMBL2368517,NaN,NaN,370.43,0.0,3.42,12f,CCCCCCCCc1cccc(NC(=O)[C@@H](N)CCP(=O)(O)O)c1,Emax,'=',...,CHEMBL1144572,1,Scientific Literature,Bioorg Med Chem,2007.0,CHEMBL3706569,NaN,NaN,NaN,0.00

In [226]:
# Number of rows
len(data)

11625

In [227]:
# Check columns
data.columns

Index(['Molecule ChEMBL ID', 'Molecule Name', 'Molecule Max Phase',
       'Molecular Weight', '#RO5 Violations', 'AlogP', 'Compound Key',
       'Smiles', 'Standard Type', 'Standard Relation', 'Standard Value',
       'Standard Units', 'pChEMBL Value', 'Data Validity Comment', 'Comment',
       'Uo Units', 'Ligand Efficiency BEI', 'Ligand Efficiency LE',
       'Ligand Efficiency LLE', 'Ligand Efficiency SEI', 'Potential Duplicate',
       'Assay ChEMBL ID', 'Assay Description', 'Assay Type', 'BAO Format ID',
       'BAO Label', 'Assay Organism', 'Assay Tissue ChEMBL ID',
       'Assay Tissue Name', 'Assay Cell Type', 'Assay Subcellular Fraction',
       'Assay Parameters', 'Assay Variant Accession', 'Assay Variant Mutation',
       'Target ChEMBL ID', 'Target Name', 'Target Organism', 'Target Type',
       'Document ChEMBL ID', 'Source ID', 'Source Description',
       'Document Journal', 'Document Year', 'Cell ChEMBL ID', 'Properties',
       'Action Type', 'Standard Text Value', 'Value'],
      dtype='object')

In [228]:
# Keep only relevant columns
df = data[['Molecule ChEMBL ID', 'Smiles', 'Standard Value', 'Standard Type', 'pChEMBL Value']]

In [230]:
## check null , duplicates values
df.isnull().sum()

Molecule ChEMBL ID       0
Smiles                   0
Standard Value        3922
Standard Type            0
pChEMBL Value         7199
dtype: int64

In [231]:
# Drop duplicates
df = df.drop_duplicates()

In [232]:
# Drop rows where pChEMBL Value is missing
df = df.dropna(subset=['pChEMBL Value'])

In [233]:
# Reset index
df = df.reset_index(drop=True)

In [234]:
# Classify compounds
# Here we assume pChEMBL >= 6 is Active, < 6 is Inactive
df['Activity_Class'] = df['pChEMBL Value'].apply(lambda x: 'Active' if x >= 6 else 'Inactive')

In [235]:

# Check class distribution
print(df['Activity_Class'].value_counts())

Activity_Class
Active      3399
Inactive     623
Name: count, dtype: int64

In [236]:
df.head()

,Molecule ChEMBL ID,Smiles,Standard Value,Standard Type,pChEMBL Value,Activity_Class
0,CHEMBL4092538,CCc1ccc(COc2ccc3c(c2)CCC(CN2CC(C(=O)O)C2)=C3C)...,0.58,EC50,9.24,Active
1,CHEMBL389033,CCCCCCCCc1cccc(NC(=O)[C@H](N)CCP(=O)(O)O)c1,30.00,Ki,7.52,Active
2,CHEMBL5884223,N=C(NC(=O)C(NC(=O)c1ccc(Cl)c(Cl)c1)c1ccc(Cl)c(...,426.00,IC50,6.37,Active
3,CHEMBL5758543,CC(C)(C)OC(=O)NC(C(=O)NC(C(=O)NC(=N)c1ccccc1)c...,475.00,IC50,6.32,Active
4,CHEMBL6053560,CCOC(=O)NC(C(=O)NC(C(=O)NC(=N)c1ccccc1)c1cccc(...,1200.00,IC50,5.92,Inactive

In [237]:
df.to_csv('S1PR1_dataset.csv', index=False)