In [ ]:
## https://go.drugbank.com/releases/latest#open-data link for DRUGBANK dataset downloaded sdf format "open structures.sdf"

## The sdf format file viewed in Discovery studio and extracted common names and Smiles and saved as "VS_new_compounds.csv" data

In [2]:
!pip install rdkit

Collecting rdkit
  Downloading rdkit-2025.3.6-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from rdkit) (2.0.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit) (11.3.0)
Downloading rdkit-2025.3.6-cp312-cp312-manylinux_2_28_x86_64.whl (36.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.1/36.1 MB 50.7 MB/s eta 0:00:00
Installing collected packages: rdkit
Successfully installed rdkit-2025.3.6

In [11]:
from rdkit import Chem
import pandas as pd

In [ ]:
sdf_file = "/content/open structures.sdf" 
supplier = Chem.SDMolSupplier(sdf_file)

In [15]:
## Extract Common names and SMILES
smiles_list = []
common_name_list = []

for mol in supplier:
    if mol is None:
        continue  # skip invalid molecules
    # SMILES
    smiles = Chem.MolToSmiles(mol)

    # Common name from SDF property
    common_name = mol.GetProp("COMMON_NAME") if mol.HasProp("COMMON_NAME") else "No name"

    smiles_list.append(smiles)
    common_name_list.append(common_name)

[14:16:25] Warning: ambiguous stereochemistry - zero final chiral volume - at atom 36 ignored
[14:16:25] Explicit valence for atom # 13 Cl, 5, is greater than permitted
[14:16:25] ERROR: Could not sanitize molecule ending on line 126776
[14:16:25] ERROR: Explicit valence for atom # 13 Cl, 5, is greater than permitted
[14:16:25] Explicit valence for atom # 19 O, 2, is greater than permitted
[14:16:25] ERROR: Could not sanitize molecule ending on line 171722
[14:16:25] ERROR: Explicit valence for atom # 19 O, 2, is greater than permitted
[14:16:25] The bonds on one end of an atropisomer are both UP or both DOWN - atoms are: 4 5
[14:16:26] Explicit valence for atom # 15 O, 3, is greater than permitted
[14:16:26] ERROR: Could not sanitize molecule ending on line 260017
[14:16:26] ERROR: Explicit valence for atom # 15 O, 3, is greater than permitted
[14:16:26] Warning: ambiguous stereochemistry - overlapping neighbors  - at atom 16 ignored
[14:16:26] Warning: ambiguous stereochemistry - opposing bonds have opposite wedging - at atom 20 ignored.
[14:16:26] Warning: ambiguous stereochemistry - opposing bonds have opposite wedging - at atom 20 ignored.
[14:16:26] Warning: ambiguous stereochemistry - zero final chiral volume - at atom 4 ignored
[14:16:27] Explicit valence for atom # 0 Be, 4, is greater than permitted
[14:16:27] ERROR: Could not sanitize molecule ending on line 467095
[14:16:27] ERROR: Explicit valence for atom # 0 Be, 4, is greater than permitted
[14:16:28] Warning: ambiguous stereochemistry - opposing bonds have opposite wedging - at atom 20 ignored.
[14:16:28] Warning: ambiguous stereochemistry - opposing bonds have opposite wedging - at atom 20 ignored.
[14:16:28] Explicit valence for atom # 28 N, 4, is greater than permitted
[14:16:28] ERROR: Could not sanitize molecule ending on line 532575
[14:16:28] ERROR: Explicit valence for atom # 28 N, 4, is greater than permitted
[14:16:28] Both bonds on one end of an atropisomer are on the same side - atoms is : 3
[14:16:28] Explicit valence for atom # 1 Cl, 4, is greater than permitted
[14:16:28] ERROR: Could not sanitize molecule ending on line 621607
[14:16:28] ERROR: Explicit valence for atom # 1 Cl, 4, is greater than permitted
[14:16:29] Both bonds on one end of an atropisomer are on the same side - atoms is : 17
[14:16:29] Warning: ambiguous stereochemistry - zero final chiral volume - at atom 85 ignored
[14:16:29] Warning: ambiguous stereochemistry - zero final chiral volume - at atom 114 ignored
[14:16:29] Both bonds on one end of an atropisomer are on the same side - atoms is : 12
[14:16:29] WARNING: not removing hydrogen atom without neighbors
[14:16:29] WARNING: not removing hydrogen atom without neighbors
[14:16:30] Both bonds on one end of an atropisomer are on the same side - atoms is : 5
[14:16:30] WARNING: could not find number of expected rings. Switching to an approximate ring finding algorithm.
[14:16:30] Explicit valence for atom # 0 B, 5, is greater than permitted
[14:16:30] ERROR: Could not sanitize molecule ending on line 859206
[14:16:30] ERROR: Explicit valence for atom # 0 B, 5, is greater than permitted
[14:16:30] WARNING: not removing hydrogen atom without neighbors
[14:16:30] WARNING: not removing hydrogen atom without neighbors
[14:16:30] WARNING: not removing hydrogen atom without neighbors
[14:16:30] WARNING: not removing hydrogen atom without neighbors
[14:16:30] WARNING: not removing hydrogen atom without neighbors
[14:16:30] Both bonds on one end of an atropisomer are on the same side - atoms is : 3

In [16]:
# Create DataFrame
df_drugbank = pd.DataFrame({"Common_Name": common_name_list, "SMILES": smiles_list})
df_drugbank.head(20)  # view first 20 molecules

             Common_Name                                             SMILES
0            Bivalirudin  CC[C@H](C)[C@H](NC(=O)[C@H](CCC(=O)O)NC(=O)[C@...
1              Goserelin  CC(C)C[C@H](NC(=O)[C@@H](COC(C)(C)C)NC(=O)[C@H...
2           Gramicidin D  CC(C)C[C@@H](NC(=O)CNC(=O)[C@@H](NC=O)C(C)C)C(...
3           Desmopressin  N=C(N)NCCC[C@@H](NC(=O)[C@@H]1CCCN1C(=O)[C@@H]...
4             Cetrorelix  CC(=O)N[C@H](Cc1ccc2ccccc2c1)C(=O)N[C@H](Cc1cc...
5             Daptomycin  CCCCCCCCCC(=O)N[C@@H](Cc1c[nH]c2ccccc12)C(=O)N...
6           Cyclosporine  C/C=C/C[C@@H](C)[C@@H](O)[C@H]1C(=O)N[C@@H](CC...
7               Abarelix  CC(=O)N[C@H](Cc1ccc2ccccc2c1)C(=O)N[C@H](Cc1cc...
8    Pyridoxal phosphate                       Cc1ncc(COP(=O)(O)O)c(C=O)c1O
9         Cyanocobalamin  C/C1=C2/N=C(/C=C3\N=C(/C(C)=C4/[C@@H](CCC(N)=O...
10  Tetrahydrofolic acid  Nc1nc(=O)c2c([nH]1)NCC(CNc1ccc(C(=O)N[C@@H](CC...
11             Histidine                         N[C@@H](Cc1c[nH]cn1)C(=O)O
12          Ademetionine  C[S+](CC[C@H](N)C(=O)[O-])C[C@H]1O[C@@H](n2cnc...
13          Pyruvic acid                                       CC(=O)C(=O)O
14         Phenylalanine                           N[C@@H](Cc1ccccc1)C(=O)O
15                Biotin          O=C(O)CCCC[C@@H]1SC[C@@H]2NC(=O)N[C@@H]21
16               Choline                                     C[N+](C)(C)CCO
17                Lysine                                NCCCC[C@H](N)C(=O)O
18              Arginine                           N=C(N)NCCC[C@H](N)C(=O)O
19         Ascorbic acid                    O=C1O[C@H]([C@@H](O)CO)C(O)=C1O

In [18]:
# Drop rows with empty SMILES
df_drugbank = df_drugbank[df_drugbank['SMILES'] != ""].reset_index(drop=True)
print(df_drugbank.shape)

(12309, 2)

In [19]:
df_drugbank

              Common_Name                                             SMILES
0             Bivalirudin  CC[C@H](C)[C@H](NC(=O)[C@H](CCC(=O)O)NC(=O)[C@...
1               Goserelin  CC(C)C[C@H](NC(=O)[C@@H](COC(C)(C)C)NC(=O)[C@H...
2            Gramicidin D  CC(C)C[C@@H](NC(=O)CNC(=O)[C@@H](NC=O)C(C)C)C(...
3            Desmopressin  N=C(N)NCCC[C@@H](NC(=O)[C@@H]1CCCN1C(=O)[C@@H]...
4              Cetrorelix  CC(=O)N[C@H](Cc1ccc2ccccc2c1)C(=O)N[C@H](Cc1cc...
...                   ...                                                ...
12304       Tulmimetostat  COC1CN([C@H]2CC[C@H]([C@@]3(C)Oc4c(Cl)cc(C(=O)...
12305        Ibuzatrelvir  COC(=O)N[C@H](C(=O)N1C[C@H](C(F)(F)F)C[C@H]1C(...
12306        Cetyl oleate         CCCCCCCC/C=C\CCCCCCCC(=O)OCCCCCCCCCCCCCCCC
12307  Cetyl myristoleate             CCCC/C=C\CCCCCCCC(=O)OCCCCCCCCCCCCCCCC
12308  Cetyl palmitoleate           CCCCCC/C=C\CCCCCCCC(=O)OCCCCCCCCCCCCCCCC

[12309 rows x 2 columns]

In [20]:
## save to csv
df_drugbank.to_csv("VS_new_compounds.csv", index=False)